from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List

from app.core.database import get_db
from app.core.security import get_current_user
from app.models.user import User
from app.models.ai_system import AISystem
from app.models.document import Document, DocumentType, DocumentStatus
from app.schemas.document import DocumentCreate, DocumentResponse, DocumentGenerateRequest

router = APIRouter()


# Document templates for generation
DOCUMENT_TEMPLATES = {
    DocumentType.TECHNICAL_DOCUMENTATION: """
# Technical Documentation - {system_name}

## 1. General Description
**System Name:** {system_name}
**Version:** {version}
**Use Case:** {use_case}
**Sector:** {sector}

## 2. Intended Purpose
{description}

## 3. System Architecture
[Describe the overall architecture, components, and data flow]

## 4. Training Data
- Data sources used
- Data preprocessing steps
- Data quality measures

## 5. Model Information
- Algorithm/model type
- Training methodology
- Performance metrics

## 6. Input/Output Specifications
- Expected inputs
- Output format and interpretation

## 7. Limitations and Risks
- Known limitations
- Identified risks and mitigations

## 8. Human Oversight Measures
- Human-in-the-loop mechanisms
- Override capabilities

## 9. Logging and Monitoring
- What is logged
- Monitoring procedures

---
Generated by EU AI Act Compliance Tool
""",
    
    DocumentType.RISK_ASSESSMENT: """
# Risk Assessment Report - {system_name}

## Executive Summary
This document presents the risk assessment for {system_name}, an AI system used for {use_case}.

**Risk Level:** {risk_level}
**Assessment Date:** {date}

## 1. System Overview
{description}

## 2. Risk Classification
Based on EU AI Act criteria, this system is classified as **{risk_level}** risk.

### Classification Rationale
{classification_reasons}

## 3. Identified Risks

### 3.1 Data-Related Risks
- [ ] Data quality issues
- [ ] Bias in training data
- [ ] Privacy concerns

### 3.2 Model-Related Risks
- [ ] Accuracy limitations
- [ ] Robustness issues
- [ ] Explainability gaps

### 3.3 Deployment Risks
- [ ] Misuse potential
- [ ] Human oversight gaps
- [ ] Integration risks

## 4. Mitigation Measures
{recommendations}

## 5. Compliance Requirements
{requirements}

## 6. Next Steps
{next_steps}

---
Generated by EU AI Act Compliance Tool
""",

    DocumentType.CONFORMITY_DECLARATION: """
# EU Declaration of Conformity

## AI System Identification
**System Name:** {system_name}
**Version:** {version}
**Manufacturer/Provider:** {company_name}

## Declaration
We hereby declare that the AI system identified above has been designed and developed in conformity with the requirements of Regulation (EU) 2024/1689 (EU AI Act).

## Applicable Requirements
The following requirements have been addressed:

- [ ] Article 9 - Risk Management System
- [ ] Article 10 - Data and Data Governance
- [ ] Article 11 - Technical Documentation
- [ ] Article 12 - Record-keeping
- [ ] Article 13 - Transparency and Information
- [ ] Article 14 - Human Oversight
- [ ] Article 15 - Accuracy, Robustness, Cybersecurity

## Conformity Assessment
**Assessment Type:** Internal control (Annex VI)
**Date of Assessment:** {date}

## Responsible Person
**Name:** _______________
**Title:** _______________
**Date:** _______________
**Signature:** _______________

---
Generated by EU AI Act Compliance Tool
"""
}


@router.post("/", response_model=DocumentResponse, status_code=status.HTTP_201_CREATED)
def create_document(
    doc_data: DocumentCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Create a new document."""
    document = Document(
        owner_id=current_user.id,
        title=doc_data.title,
        document_type=doc_data.document_type,
        ai_system_id=doc_data.ai_system_id,
        content=doc_data.content
    )
    db.add(document)
    db.commit()
    db.refresh(document)
    return document


@router.get("/", response_model=List[DocumentResponse])
def list_documents(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """List all documents for the current user."""
    documents = db.query(Document).filter(Document.owner_id == current_user.id).all()
    return documents


@router.get("/{document_id}", response_model=DocumentResponse)
def get_document(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Get a specific document."""
    document = db.query(Document).filter(
        Document.id == document_id,
        Document.owner_id == current_user.id
    ).first()
    
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )
    return document


@router.post("/generate", response_model=DocumentResponse)
def generate_document(
    request: DocumentGenerateRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Generate a compliance document for an AI system."""
    # Get the AI system
    ai_system = db.query(AISystem).filter(
        AISystem.id == request.ai_system_id,
        AISystem.owner_id == current_user.id
    ).first()
    
    if not ai_system:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="AI system not found"
        )
    
    # Get template
    template = DOCUMENT_TEMPLATES.get(request.document_type)
    if not template:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"No template available for {request.document_type}"
        )
    
    # Get latest risk assessment if available
    from app.models.ai_system import RiskAssessment
    assessment = db.query(RiskAssessment).filter(
        RiskAssessment.ai_system_id == ai_system.id
    ).order_by(RiskAssessment.assessed_at.desc()).first()
    
    # Fill template
    from datetime import datetime
    content = template.format(
        system_name=ai_system.name,
        version=ai_system.version or "1.0",
        use_case=ai_system.use_case or "Not specified",
        sector=ai_system.sector or "Not specified",
        description=ai_system.description or "No description provided",
        risk_level=ai_system.risk_level.value if ai_system.risk_level else "Not assessed",
        date=datetime.utcnow().strftime("%Y-%m-%d"),
        company_name=current_user.company_name or "Not specified",
        classification_reasons="See risk assessment details",
        recommendations="Based on risk assessment",
        requirements="See applicable requirements above",
        next_steps="Complete all checklist items"
    )
    
    # Create document
    document = Document(
        owner_id=current_user.id,
        ai_system_id=ai_system.id,
        title=f"{request.document_type.value.replace('_', ' ').title()} - {ai_system.name}",
        document_type=request.document_type,
        status=DocumentStatus.GENERATED,
        content=content
    )
    db.add(document)
    db.commit()
    db.refresh(document)
    
    return document


@router.delete("/{document_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_document(
    document_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Delete a document."""
    document = db.query(Document).filter(
        Document.id == document_id,
        Document.owner_id == current_user.id
    ).first()
    
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )
    
    db.delete(document)
    db.commit()
