"""alter_sector_to_enum

Revision ID: 85d6d890e592
Revises: dbd6fdf84641
Create Date: 2026-05-12 19:04:23.915795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d6d890e592'
down_revision: Union[str, Sequence[str], None] = 'dbd6fdf84641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the ENUM type first
    from sqlalchemy.dialects import postgresql
    sector_enum = postgresql.ENUM('healthcare', 'education', 'employment', 'law_enforcement', 'critical_infrastructure', 'finance', 'migration', 'justice', 'other', name='sectorenum', create_type=False)
    sector_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_systems', 'sector',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('healthcare', 'education', 'employment', 'law_enforcement', 'critical_infrastructure', 'finance', 'migration', 'justice', 'other', name='sectorenum'),
               existing_nullable=True,
               postgresql_using="sector::sectorenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_systems', 'sector',
               existing_type=sa.Enum('healthcare', 'education', 'employment', 'law_enforcement', 'critical_infrastructure', 'finance', 'migration', 'justice', 'other', name='sectorenum'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###

    # Drop the ENUM type
    from sqlalchemy.dialects import postgresql
    sector_enum = postgresql.ENUM('healthcare', 'education', 'employment', 'law_enforcement', 'critical_infrastructure', 'finance', 'migration', 'justice', 'other', name='sectorenum', create_type=False)
    sector_enum.drop(op.get_bind(), checkfirst=True)
